global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "albums_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "albums-application:8080",
            "albums-notification-service:8083",
            "albums-audit-service:8082",
            "albums-analytics-service:8081",
          ]
