spring.application.name=albums-application

dgs.graphql.schema-locations=classpath*:/graphql-client/**/*.graphqls

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ???????? publisher confirms. correlated - ??? ????????????, simple - ?????? true/false
spring.rabbitmq.publisher-confirm-type=correlated
# ???????? publisher returns, ????? ?????, ???? ????????? ?? ????? ?? ???????
spring.rabbitmq.publisher-returns=true
# ?????? ??? RabbitTemplate, ????? ??? ????????? ?? ????????? ???? ??????????????
spring.rabbitmq.template.mandatory=true

spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.rabbitmq.listener.simple.retry.enabled=false

grpc.client.analytics-service.address=static://localhost:9090
grpc.client.analytics-service.negotiation-type=plaintext






management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans

management.metrics.export.prometheus.enabled=true

spring.rabbitmq.template.observation-enabled=true

spring.rabbitmq.listener.simple.observation-enabled=true
